baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'Alfred Dobradi'
paginate = 5

[menu]
[[menu.main]]
    identifier = "home"
    url = "/"
    name = "Home"
    weight = -300
[[menu.main]]
    identifier = "topics"
    url = "/topics"
    name = "Topics"
    weight = 200

[module]
[[module.imports]]
    path = "neominimal"

[taxonomies]
    topic = 'topics'